# Generated by Django 2.1 on 2019-05-07 14:27

from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('industry_type', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, validators=[users.utils.validate_phone_number])),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentcareer',
            name='job_title',
        ),
        migrations.AddField(
            model_name='studentcareer',
            name='job_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentcareer',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentcareer',
            name='enrollment_status',
            field=models.CharField(blank=True, choices=[('0', 'Full-time'), ('1', 'Intern')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentcareer',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('1', '50,000 to 60,000'), ('2', '60,000 to 70,000'), ('3', '70,000 to 80,000'), ('4', '80,000 to 90,000'), ('5', '90,000 to 100,000')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentcareer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='studentcareer',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
        ),
    ]
