# Generated by Django 2.1 on 2019-05-07 17:35

from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190507_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=2)),
                ('phone_number', models.CharField(max_length=20, validators=[users.utils.validate_phone_number])),
                ('major1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser')),
            ],
        ),
    ]
